# Generated by Django 4.2.7 on 2024-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время записи'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время обновления'),
        ),
    ]
