# Generated by Django 4.2.7 on 2024-10-30 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_alter_cars_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('id',), 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
    ]
